micronaut:
  application:
    name: oda-kick-service
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          jwks:
            keycloak:
              url: ${JWKS_URI}
  executors:
    command-listener:
      type: fixed
      nThreads: 1
    event-listener:
      type: fixed
      nThreads: 1
  http:
    services:
      kick-web:
        url: https://kick.com
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
flyway:
  datasources:
    default:
      enabled: true
endpoints:
  prometheus:
    sensitive: false
  metrics:
    sensitive: false
